language: node_js
node_js:
- '6.9'
cache:
  directories:
    - node_modules
branches:
  only:
  - rs_master
install: "npm i && npm update"
before_deploy:
  - npm run build
script: echo "skipping npm test for RS build"
deploy:
  - provider: s3
    bucket: governance-policies-docs
    region: us-east-1
    skip_cleanup: true
    local_dir: $TRAVIS_BUILD_DIR/$WORK_DIR/dist
    upload_dir: /
    acl: public_read
    access_key_id: "$gov_api_docs_access_key"
    secret_access_key: "$gov_api_docs_secret_key"
    on:
      branches:
        only:
          - rs_master
