language: node_js
node_js:
- '6.9'
cache:
  directories:
    - node_modules
branches:
  only:
  - rs_master
install: "npm i && npm update"
before_deploy:
  - npm run build
script: echo "skipping npm test for RS build"
deploy:
  - provider: s3
    bucket: rs-api-docs
    upload_dir: governance-policies
    region: us-east-1
    skip_cleanup: true
    local_dir: $TRAVIS_BUILD_DIR/$WORK_DIR/dist
    acl: public_read
    access_key_id: "$RS_API_DOCS_S3_KEY_ID"
    secret_access_key: "$RS_API_DOCS_S3_KEY_SECRET"
    on:
      branch: rs_master
