---
url: "https://s3.amazonaws.com/governance-policies-docs/governance/front_service/master/swagger.json"
dom_id: "#swagger-ui"
validatorUrl: "https://online.swagger.io/validator"
oauth2RedirectUrl: "http://localhost:3200/oauth2-redirect.html"
